= Política Agile del Ayuntamiento de Barcelona
:experimental:
:icons: font
:page-partial:
:source-highlighter: highlightjs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

include::{partialsdir}/README.adoc[tag=metadata]

Esta sección presenta los principios generales y directivos de la política Agile del Ayuntamiento de Barcelona, elaborados a partir de los estándares de servicios digitales del Ayuntamiento de Barcelona, dentro del marco del Plan de transformación digital para el Ayuntamiento de Barcelona.
Los objetivos más relevantes con respecto a las metodologías ágiles son los siguientes:


* *Poner más interés en la persona usuaria final:*

** Dar poder a la persona usuaria final en la toma de decisiones.
** Ser más flexible y entregar más valor.

* *Transformar la cultura organizativa:*

** Poner énfasis en la colaboración y la transparencia.
** Centrar la orientación más hacia el valor manteniendo el control de los desarrollos.

* *Acortar el tiempo de desarrollo:*

** Mejorar, a la vez, la calidad técnica.
** Entregar más frecuentemente, de manera fiable, para adelantar el retorno de la inversión.

* *Implementar la mejora continua:*

** Sistematizar la mejora continua basada en ciclos cortos de inspección y adaptación.
** Dotar la organización de agentes activos de la mejora sistémica y de los equipos.

////
L'aplicació d'aquests principis i directrius es farà a través de la realització dels projectes de transformació digital àgil de l'Ajuntament, gestionats principalment per l'IMI.
Aquests projectes permetran la dedicació de recursos, la creació d'infraestructura i l'adquisició de competències per a portar a terme aquestes transformacions.
D'aquesta manera, la gestió del canvi que suposa l'aplicació d'aquestes pràctiques dins de l'Ajuntament es farà de manera iterativa a través de projectes concrets.
Alguns projectes i les seves ampliacions (per exemple, Decidim.Barcelona) ja compleixen en bona mesura les directrius indicades aquí, uns altres ho aniran aconseguint amb un procés d'implementació més progressiu.
////

== Principios generales y directivos de la política Agile del Ayuntamiento de Barcelona

Tal como se definen en el documento “Directrices para la prestación de servicios digitales Agile del Ayuntamiento de Barcelona”, los principios generales en el desarrollo Agile dentro de las entidades del Ayuntamiento son los siguientes:

[upperalpha]
. *Colaboración interdisciplinaria.* -
Se configuran equipos multidisciplinares con personas provenientes de diversas disciplinas o entornos de trabajo, en los que todo el mundo está completamente implicado y que incluyen los roles y las especialidades necesarias para desarrollar aplicaciones, servicios y procesos.
Sólo una o dos personas son directamente responsables, pero el éxito del equipo recae por igual en todos los miembros.

. *Equipos organizados.*
Los equipos que se organizan de forma autónoma y flexible pueden crear nuevos enfoques y adaptarse a nuevos retos por sí mismos en su entorno.
En consecuencia, los roles y las responsabilidades dentro de los equipos tendrán un cierto nivel de flexibilidad y fluidez de acuerdo con la experiencia, las habilidades y los conocimientos de las personas integrantes del equipo, así como con las necesidades de los proyectos.

. *Comunicación.*
Se debe establecer un plan de comunicación teniendo en mente la transparencia y las responsabilidades de los agentes implicados.
Hay que identificar a las personas usuarias clave de los servicios y los procesos municipales, así como a los actores que participan en la parte técnica.
Todos ellos serán los destinatarios de las acciones comunicativas que deberán llevarse a cabo con una frecuencia adecuada a los objetivos y las necesidades de los proyectos.
Las conversaciones cara a cara tendrán prioridad con respecto a otros canales de comunicación.

. *Transparencia.*
Deberían compartirse, de manera abierta y transparente, con los actores clave, el estado del proyecto, las prioridades, los riesgos, los problemas y los “elementos de bloqueo” eventuales para abordar los retos con rapidez.
Y eso se puede hacer con comunicaciones directas pero también utilizando herramientas adaptadas a la metodología ágil, como los tableros Kanban.

. *Mejora continua.*
Se establecerán prácticas de trabajo colaborativo para facilitar una cultura de aprendizaje y de mejora continua, tanto del servicio prestado como de los integrantes del equipo.

. *Retroalimentación rápida.*
El equipo se esforzará por hacer iteraciones tan cortas como sea posible.
Las prácticas de equipo se harán de tal manera que faciliten la obtención rápida de la información de retroalimentación y ésta se incorpore al *_backlog_* del proyecto.

. *Aceptación del cambio.*
Se entiende que los planes y los proyectos evolucionarán y cambiarán a lo largo de la prestación del servicio.
Se establecerán prácticas de análisis y de planificación para reflejar este hecho.

. *Pensamiento iterativo.*
Las actividades de análisis, diseño, planificación y desarrollo adoptarán un enfoque iterativo en ciclos cortos para permitir la retroacción y cambiar las prioridades según las necesidades.

. *Despliegue rápido, despliegue frecuente.*
Hay que poner énfasis en dar valor a las personas usuarias finales tan rápidamente como sea posible, reducir el tiempo de puesta en producción de las aplicaciones y recibir retroacción de las personas usuarias lo más rápido posible.
Se dará prioridad al producto mínimo viable identificado que responda a las necesidades prioritarias de las personas usuarias y las entregas siguientes se realizarán de acuerdo con este enfoque.

. *Interés en ofrecer valor a la persona usuaria.*
Se debe dar prioridad a las necesidades de la persona usuaria.
Las necesidades de la persona usuaria van por delante de cualquier otra necesidad, incluso de las de los actores clave.
Cuando haya un conflicto de necesidades entre los grupos, hay que asegurarse de que hay unas prioridades claras.
Se promoverá la diversidad en los equipos para favorecer diseños inclusivos.

. *Calidad.*
La calidad no hace referencia solo a la calidad técnica, sino también a la calidad del servicio.
La calidad está presente en cada paso del proceso y todas las personas del equipo tienen la responsabilidad de garantizar que el servicio es de un nivel alto.

. *Medida del progreso.*
La entrega de software ejecutable es la principal medida de progreso.
También hay que aplicar otras medidas que reflejan el valor aportado a la persona usuaria y al negocio para garantizar que satisface las necesidades reales y da un valor real.

Estos principios y directrices se aplicarán en proyectos y servicios TIC a través de las prácticas y las medidas que se presentan en la sección siguiente.
