= Agile y Administración pública
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

== La práctica Agile en la Administración pública

La adopción de métodos ágiles ha sido muy lenta en el sector público, teniendo en cuenta que el Manifiesto Agile es del 2001.
No obstante, hay varios casos de implementación de metodologías ágiles documentados, como en Finlandia (un proyecto de desarrollo de _software_ para gestionar los permisos de conducir) o, más cerca, en Andalucía, con dos proyectos del Ministerio de Cultura y Deportes, _eBOJA y TOPOS_.
El primero fue un proyecto de desarrollo de sistema para el uso del diario oficial regional, y el segundo, un proyecto de infraestructura para la gestión de los sistemas del ministerio regional.
En Estados Unidos, la página web healthcare. gov se rediseñó utilizando esta metodología, y el Departamento de Defensa ha reconocido la metodología ágil y sus instrucciones para la adquisición de sistemas (Instrucción 5000.2, de 2015) que la soportan.
En el Reino Unido, la Driver and Vehicle Standards Agency, el servicio estatal de conducción, ha implementado con éxito un sistema de gestión de ITV con metodologías ágiles y contratos de corto plazo.

Por nuestra parte, en Cataluña también se ha hecho una prueba piloto para aplicar el _scrum_ a un proyecto real del IMI, para identificar las implicaciones que tenía el uso de este “marco Agile” y, sobre todo, para saber cuáles son las carencias actuales, tanto en conocimientos como en infraestructura.

Las conclusiones de estos proyectos indican que la implementación de esta metodología se hizo con éxito, pero no sin retos, tanto generales como particulares, para las entidades públicas titulares de los proyectos.
El enfoque permitió a los equipos elaborar un plan de proyecto inicial que podía guiar el proyecto y también corregirlo de acuerdo con los resultados.
También ofrece una visión relevante y útil sobre el estado del proyecto en cada momento, tanto para el equipo como para los responsables de gestionarlo y supervisarlo.
Se puede considerar un proceso de aprendizaje, en el que los equipos de personas usuarias y de desarrolladores van mejorando sus habilidades.
Adicionalmente, la metodología transforma el esfuerzo de estimación y planificación en un proceso continuo y participativo, que implica a todo el equipo, en lugar de ser una fase inicial del proyecto, propia de otras metodologías tradicionales como la de cascada.

De manera más general, diversas administraciones están en proceso de implementar estas metodologías, como el Reino Unido (_https:// www.gov.uk/service-manual/agile-delivery_), Nueva York (_http://playbook.cityofnewyork.us/_) y San Francisco (_http://digitalservices.sfgov.org_, por ejemplo, en la Human Services Agency o en el Departamento de Vivienda y desarrollo comunitario).
Estas iniciativas basan la entrega de servicios digitales innovadores, más adaptados a las personas usuarias y a unos costes más reducidos, en metodologías ágiles desde su concepción.

== Consideraciones importantes

Tal como hemos descrito en el apartado anterior, “Principios generales de desarrollo Agile”, los métodos ágiles tienen diversas consecuencias y plantean retos específicos a su implementación en el desarrollo de servicios digitales para la Administración pública.

Con respecto a la organización de proyectos, se debe asegurar un consenso entre todos los agentes implicados en el proyecto sobre qué método se tiene que utilizar; sobre la definición y la atribución de funciones o roles, en particular entre el departamento o unidad “cliente” (habitualmente, el titular del proyecto o _product owner_), la entidad que gestiona el contrato (en el Ayuntamiento de Barcelona, habitualmente será el IMI) y el proveedor; y sobre cómo llevar a cabo estos roles.
Esta selección de metodología y definición de roles es más difícil dependiendo de la complejidad organizativa de la administración destinataria y de la integración de los nuevos servicios con sistemas o plataformas existentes y con proyectos ya en marcha.
Las administraciones tienen muchos sistemas y servicios ya implementados, de manera que la coexistencia con los proyectos tradicionales puede ser complicada.

Asimismo, será importante poder disponer de equipos de proyecto estables, tanto desde el lado del cliente/usuario, como del equipo desarrollador.
La solvencia técnica, en plazos de conocimiento de los métodos ágiles y la gestión del conocimiento, vuelve a ser un aspecto esencial para garantizar el éxito de los proyectos a corto, medio y largo plazo.
Asimismo, en la metodología _scrum_, los equipos ágiles deben coordinarse con los equipos que trabajan sobre proyectos existentes o transversales de la Administración.

Además, será esencial garantizar la dedicación de los equipos “cliente/usuario” (personal de las unidades y entidades de la Administración pública) durante la evolución y el desarrollo del proyecto: no se trata de especificar unas funcionalidades y esperar su entrega.
La metodología ágil requiere fomentar una comunicación o una interacción más intensiva entre usuario y desarrollador para poder alcanzar los objetivos de las iteraciones.
Con Agile, los departamentos usuarios participan activamente durante todo el proceso y los desarrolladores están más presentes en la vida diaria de las personas usuarias para crear la visión de producto y las historias de usuario y recoger retroalimentación de manera iterativa.

Uno de los aspectos más relevantes para una Administración pública es el proceso y las obligaciones con respecto a la contratación de servicios, que deben cumplir una normativa de contratación pública no necesariamente bien adaptada a estas metodologías.
Teniendo en cuenta las características de las metodologías ágiles ya mencionadas, hay que buscar más flexibilidad cuando se contratan servicios tecnológicos ágiles (por ejemplo, dividiendo el proyecto por lotes o actividades, especificando la metodología que hay que utilizar con claridad y las tareas de cada parte, y siendo más flexible en cuanto a las especificaciones definitivas y la entrega y la aceptación de cada fase/actividad o iteración) y en el control de la ejecución del contrato una vez adjudicado.

En conclusión, es importante reconocer la necesidad de trabajar bien el cambio cultural de las administraciones públicas como aparte de la transformación ágil, ya que este cambio suele ser más lento y difícil que en el sector privado.
