[appendix]
= Más información. Referencias
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

*Documentación del Ayuntamiento de Barcelona*

* Ayuntamiento de Barcelona: “Directrices para la prestación de servicios digitales Agile”, 2017.

*Referencias:*

* Manifiesto Agile: _http://agilemanifesto.org/iso/en/manifesto.html_
* Principios Agile: _http://agilemanifesto.org/iso/en/principles.html_

*_Scrum_*

* *“The Scrum Guide”, Schwaber and Sutherland.*
Este documento de diecisiete páginas es la definición oficial de _Scrum_.
Se recomienda encarecidamente leerlo para entender la filosofía de este marco de trabajo, así como sus componentes y reglas.

* *Scrum Pocket Guide, Verheyen.*
Este librito, de aproximadamente 100 páginas, es una ampliación comentada de “_The Scrum Guide_”.
Se recomienda leerlo si se quiere tener un buen conocimiento teórico del marco de trabajo.

* *_Large-Scale Scrum_, Larman & Bodde.*
Este libro describe el modelo _large-scale scrum_ (LeSS) para aplicar Scrum a equipos múltiples, por lo que contiene contenidos avanzados.
No obstante, también revisa de manera reflexiva y detallada los conceptos básicos de _Scrum_, además de introducir muchos otros conceptos más avanzados.

*Definir productos y _backlogs_*

* *_User Stories Applied_, Cohn.*
Este libro es una guía práctica para entender qué son las historias de usuario y cómo hacer un buen uso de las mismas.

* *_User Story Mapping_, Patton.*
Este libro profundiza en la utilidad de la técnica del mapeo de historias para entender mejor los problemas del usuario y aprender a diseñar planes de desarrollo rápidos y que aprovechen las entregas frecuentes para optimizar el valor que se ofrece a las personas usuarias.

*Planificación ágil*

* *_Agile Estimating and Planning_, Cohn.*
Este libro es una guía práctica sobre el proceso de estimar el esfuerzo de los _backlogs_ de producto y sobre cómo utilizar estas estimaciones para planificar versiones y _sprints_ y hacer el seguimiento de los planes.

* *_Scrum & XP from the trenches_, Kniberg.*
Este libro se puede descargar libremente de la web InfoQ.
Es una guía completa y pragmática sobre cómo hacer un desarrollo utilizando _Scrum_ y _eXtreme Programming_.

* *_Agile Project Management with Scrum_, Schwaber.*
Este libro recoge la experiencia práctica del cocreador de _scrum_ en su aplicación en diversas empresas y explican lo que fue bien y lo que no funcionó.

*_Product Owner_*

* *_AGILE Product Management with Scrum_.*
Este libro hace una buena introducción al rol de _product owner_, a sus responsabilidades y a cómo llevar a cabo las actividades habituales durante el ciclo de vida de un producto.

* *_Scrum Product Ownership, Galen_.*
Este libro explica cómo desarrollar el rol de _Product owner_, tanto en organizaciones pequeñas como en organizaciones grandes, e incluye especialmente los aspectos de organización con todos los actores involucrados.

*_Scrum Master_*

* *_Scrum Mastery_, Watts.*
Este libro describe, de una manera ágil y amena, el enfoque correcto del rol del _Scrum master_.
Es una introducción muy recomendable.

* *_Coaching Agile Teams_, Adkins.*
Este libro es una referencia avanzada para cualquier _coach_ y _scrum master_ profesional.
Es muy detallado y contiene conceptos avanzados.

* *_Succeeding with AGILE_, Cohn.*
Este libro explica patrones para extender la agilidad en las organizaciones.
No hay ninguna metodología unificada para introducir la agilidad en las empresas; estos consejos pueden ser útiles para aplicar al contexto único de cada organización.

*Otra documentación consultada*

Gobierno del Reino Unido. “Agile Delivery”, _https://www.gov.uk/service-manual/agile-delivery_

Nuottila J., Aaltonen K., Kujala J. “_Challenges of adopting agile methods in a public Organization_”, International Journal of Information Systems and Project Management, vol. 4, No. 3 (2016), pp. 65-85, DOI: 10.12821/ijispm040304.

Torrecilla-Salinas C. J., Sedeño J., Escalona M. J., Mejías M. “_Agile in Public Administration: Oxymoron_ _or reality? An experience report_”, CAiSE Industry Track, vol. 1017 of CEUR Workshop Proceedings, pp.1-8, CEUR-WS.org (2013), en línea a  _http://ceur-ws.org/Vol-1017/Paper1CAiSE_IT2013.pdf_

Software Engineering Institute of the CMU. “_Contracting for Agile Software Development in the Department of Defense: An Introduction_” (August 2015), en línia a _https://resources.sei.cmu.edu/asset_files/TechnicalNote/2015_004_001_442515.pdf_

US Government Accountability Office. “_Software Development: Effective Practices and Federal Challenges in Applying Agile Methods_”, GAO-12-681, en línea a _http://www.gao.gov/assets/600/593091.pdf_

Balter B. “_Towards a More Agile Government_”, 41 Pub. Cont. L. J. 149, The Public Contract Law Journal (autumn 2011), en línia a _https://ben.balter.com/2011/11/29/towards-a-more-agile-government/_
